# Generated by Django 6.0.3 on 2026-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='currency',
            field=models.CharField(default='Ksh', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.09, max_digits=5),
        ),
    ]
