# Generated by Django 6.0.3 on 2026-03-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shop_is_active_alter_shop_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='receipt_footer',
            field=models.TextField(blank=True, help_text='Text shown at the bottom of receipts', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='receipt_header',
            field=models.TextField(blank=True, help_text='Text shown at the top of receipts', null=True),
        ),
    ]
