# Generated by Django 6.0.3 on 2026-03-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_alert_quantity_brand_product_brand_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='api.shop'),
        ),
    ]
